version: '2'
services:
  web:
    image: demo:latest
    environment:
      JAVA_OPTS: -Xms200m -Xmx380m -XX:MaxMetaspaceSize=100m -Duser.timezone=Europe/Bucharest -Djava.security.egd=file:/dev/./urandom
    ports:
      - "8080:8080"
