spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: demo
    password: demo
    hikari:
      maximum-pool-size: 2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
